LineLength:
  Enabled: false

StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true

Documentation:
  Enabled: false

Style/FileName:
  Exclude:
    - 'lib/jekyll-twitter-plugin.rb'

Lint/AssignmentInCondition:
  Enabled: false

AllCops:
  Exclude:
    - 'spec/integration_tests.rb'
